title: Intro to GitHub
description: >-
  In this course you will introduce to GitHub. And learn how to use GitHub and
  get Benefits of it.
template:
  repo: intro-to-github-template
  name: intro-to-github
before:
  - type: createIssue
    title: Welcome!
    body: new-issue.md
  - type: createIssue
steps:
  - title: First step
    description: The first step in your course
    event: installation
    link: '{{ repoUrl }}'
    actions:
      - type: createIssue
        title: We have an issue for you
  - title: New step
    actions:
      - type: createIssue
        title: A new issue
        body: a-response-file.md
